library('ggplot2')
library('plotly')
library('RVAideMemoire')
library('dplyr')
library('tidyverse')
library('kableExtra')
library('broom')
library('reshape2')
source('f_generate_data.R')
source('f_get_vars.R')
source('f_make_difference_df.R')
source('f_overall_p.R')
data <- generate_data()
categorical_variables <- get_categorical_vars(data)
numeric_variables <- get_numerical_vars(data)
difference_df <- make_dif_df(data, numeric_variables, categorical_variables)
