---
title: "R Notebook"
output: html_notebook
---

The [R plugin](https://www.jetbrains.com/help/pycharm/r-plugin-support.html) for IntelliJ-based IDEs provides
handy capabilities to work with the [R Markdown](https://www.jetbrains.com/help/pycharm/r-markdown.html) files.
To [add](https://www.jetbrains.com/help/pycharm/r-markdown.html#add-code-chunk) a new R chunk,
position the caret at any line or the code chunk, then click "+".

The code chunk appears:
```{r}
source('scripts/0_preprocessing/preprocessing.R')
data<-preprocessing(filename='data/Data_SAS.xlsx', output='scripts/_misc/Data_SAS_fixed.xlsx')
str(data)
```
```{r}
data$gender <- as.integer(as.factor(data$gender))
data$antipsychotic <-  as.integer(as.factor(data$antipsychotic))
data$`antipsychotic generation` <- as.numeric(data$`antipsychotic generation`)
data$course <-  as.integer(as.factor(data$course))
data$education <-  as.integer(as.factor(data$education))
data$smoke <- as.numeric(data$smoke)
data$visit <- as.numeric(data$visit)
data$id <- NA
data$`antipsychotic dose`
```
```{r}
library("corrplot")
library("FactoMineR")
numerical_data <- data[2:ncol(data)]
corr_matrix <- cor(numerical_data)
corrplot(corr_matrix)
data.pca <- princomp(corr_matrix)
fviz_eig(data.pca, addlabels = TRUE)
fviz_cos2(data.pca, choice = "var", axes = 1:2)
```
```{r}
numerical_data <- data[2:ncol(data)][data$visit==1,][,-11]
corr_matrix <- cor(numerical_data)
corrplot(corr_matrix)
data.pca <- princomp(corr_matrix)
fviz_eig(data.pca, addlabels = TRUE)
fviz_cos2(data.pca, choice = "var", axes = 1:2)
```
```{r}

numerical_data <- data[2:ncol(data)][data$visit==2,][,-11]
corr_matrix <- cor(numerical_data)
corrplot(corr_matrix)
data.pca <- princomp(corr_matrix)
fviz_eig(data.pca, addlabels = TRUE)
fviz_cos2(data.pca, choice = "var", axes = 1:2)
```
```{r}

```
